// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcWyaE0VRhbK46clCD6_kFyjNHO82t1Q',
    appId: '1:747000703568:web:32dcabe6e4253410b3ff55',
    messagingSenderId: '747000703568',
    projectId: 'groconnect-43349',
    authDomain: 'groconnect-43349.firebaseapp.com',
    storageBucket: 'groconnect-43349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE83m1l-hsQc7OYmY4J5iAvZkfFvdTLxM',
    appId: '1:747000703568:android:92b5019d7e579329b3ff55',
    messagingSenderId: '747000703568',
    projectId: 'groconnect-43349',
    storageBucket: 'groconnect-43349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJw1Asqfd4XEPgy3AfIXnrIMj17AInO0',
    appId: '1:747000703568:ios:0597553baeb8d700b3ff55',
    messagingSenderId: '747000703568',
    projectId: 'groconnect-43349',
    storageBucket: 'groconnect-43349.appspot.com',
    iosBundleId: 'com.example.grocerygo',
  );
}
